apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 50Gi
  nfs:
    path: /shares/nfs/ocp4/registry
    server: 192.168.4.102
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
