apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-provider-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://api.managed.foo.bar:6443'
  source:
    path: manifests/identity-provider/overlays/dev
    repoURL: 'ssh://git@gitlab.consulting.redhat.com:2222/dev/ansible_argocd.git'
    targetRevision: 'master'
  project: default
  syncPolicy:
    automated: {}
