bases:
- ../../base

patchesStrategicMerge:
  - oauth-cr.yaml
  #- idp-sealed-secret.yaml

  # useful for private repos
  # for public used kubeseal
  # oc create secret generic idp-secret --from-literal=clientSecret="secretgoeshere" --dry-run -o yaml|kubeseal -o yaml > idp-sealed-secret.yaml
  #secretGenerator:
  #  - name: idp-secret
  #    files:
  #      - clientSecret
  #    namespace: openshift-config
  #    type: Opaque
  #

generatorOptions:
  disableNameSuffixHash: true
