apiVersion: v1
data:
  htpasswd: ZGVtbzokMnkkMDUkUDRNQzVHWmV4V0ZCeUk3Uy5MTXRXZXRxSVRSdHBNUDJLZEh1dmY2Uk9ya1BjekxxZzlkbWE=
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
