apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migrate-metrics-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://api.managed.foo.bar:6443'
  source:
    path: manifests/migrate-metrics/overlays/dev
    repoURL: 'https://github.com/ddreggors/gitops-infra-config.git'
    targetRevision: 'master'
  project: default
  syncPolicy:
    automated: {}
